### ISSUE TITLE
error "gatsby-transformer-bibtex" threw an error while running the onCreateNode lifecycle:

### ISSUE THREAD

**Issue by awconway** [giltho/gatsby-transformer-bibtex#15]
Hi - looks like a really useful package and I'm eager to give it a try. I get the following error when trying to set it up with the simple gatsby hello world starter though. Error is below. Any advice? Thanks.

error "gatsby-transformer-bibtex" threw an error while running the onCreateNode lifecycle:

invalid syntax at index 52
Unexpected {"type":"id","string":"%"}

  158 |             content = _context.sent;
  159 |             // Parse
> 160 |             bib = (0, _bibtex.parseBibFile)(content);
      |                                            ^
  161 |             keys = Object.keys(bib.entries$);
  162 |             onlyFieldsWithKey = _lodash["default"].map(keys, function (key) {
  163 |               var obj = jsonOfEntry(bib.getEntry(key));

  Error: invalid syntax at index 52
  Unexpected {"type":"id","string":"%"}

package.json

{
  "name": "gatsby-starter-hello-world",
  "private": true,
  "description": "A simplified bare-bones starter for Gatsby",
  "version": "0.1.0",
  "license": "0BSD",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "dependencies": {
    "gatsby": "^2.25.3",
    "gatsby-source-filesystem": "^2.4.2",
    "gatsby-transformer-bibtex": "^0.1.3",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "devDependencies": {
    "prettier": "2.1.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-hello-world"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}

gatsby-config.js

/**
 * Configure your Gatsby site with this file.
 *
 * See: https://www.gatsbyjs.com/docs/gatsby-config/
 */

module.exports = {
  /* Your site config here */
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `publications`,
        path: `${__dirname}/publications`,
      },
    },
    'gatsby-transformer-bibtex',
  ],
}

**Comment by MarcelWaldvogel** [comment]
Just guessing: Could it be that the ID of your 52nd BibTeX entry starts with a `%`? Can you try removing that comment?

**Comment by awconway** [comment]
🤦‍♂️ that was the problem. 

However, I think this is still kind of a bug that should be fixed to handle inline comments. Or at least the example in the readme should be changed. I used the same example as in the readme with an 'inline' comment, which was the problem:
```
@article{some_key,
 author = {Name, Your and Of-Yours, Coauthor},
 title = {Paper A},
 file = {paper_a.pdf} % path relative to where this .bib file is
} 
```
Considering the comment was in the readme it wasn't immediately clear to me that it couldn't handle in-line comments. Removing the comment does indeed fix the error though.

**Comment by MarcelWaldvogel** [comment]
I think I remember that BibTeX itself (or at least some styles) also do not like inline comments, but haven't checked lately. Can anyone verify this, so that we can either update the documentation or handle the `%`?

**Comment by giltho** [comment]
Hello,
Very sorry for not answering any of this earlier, this year is chaotic on all levels.

-> I'm editing the readme right away to remove that line comment, and add something about not putting comments in the bibtex.
It isn't something I can fix unfortunately, because that comes from the bibtex parser, which is [this one](https://github.com/digitalheir/bibtex-js) and doesn't look like it's maintained anymore.
The main pain with gatsby-transformer-bibtex is that there is no good library to handle bibtex in JS. So far my best hope would be to compile XdkBibTeX to WASM and use that... I don't remember why right now, but citation-js was a nightmare.


Anyway, thanks for pointing that out, and sorry again for not reacting earlier !

**Comment by giltho** [comment]
Edited in 7c26ae86 and f8292966

Feel free to close the issue if that answered your questions

**Comment by awconway** [comment]
thanks
