### ISSUE TITLE
don't find entries for querying

### ISSUE THREAD

**Issue by stschiff** [giltho/gatsby-transformer-bibtex#2]
Hi,

the poor documentation of this module suggests that you cannot imagine someone else wanting to be using it :-) But I'm actually quite interested. I installed it and added it to my `gatsby-config.js`, but I cannot find any nodes in the graphiQL browser. I simply added it directly under `plugins`, without any further options. And I have the `gatsby-source-filesystem` plugin active and working. I can query for my bibtex file using 
```
 query MyQuery {
  file(relativePath: {eq: "publications.bib"}) {
    relativePath
   }
}
```

but I can't select any useful children with bibtex content. What am I doing wrong?

Thanks

**Comment by giltho** [comment]
Hey ! 
Yeah so sorry about that I definitely need to add some documentation there 😅 
I wrote the pluging a year ago and Gatsby moves pretty fast so I don't know if anything is really up to date. That being said, [this line](https://github.com/giltho/gatsby-transformer-bibtex/blob/master/src/gatsby-node.js#L58) actually creates `reference` nodes.

My current usage of it is:

```js
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `documents`,
        path: `${__dirname}/src/assets/documents`,
       }
},
```
in gatsby-config.js
where `src/assets/documents` contains my publication.bib as well as the pdf files.

and the the query component is:

```js
export default () => {
    return <StaticQuery
        query={graphql`query {
            allReference {
              edges {
                node {
                  key
                  title
                  authors
                  file {
                    publicURL
                  }
                  journal
                  date
                }
              }
            }
          }`}
        render={(data) => {
            if (data) {
                return (
                  <div className="bibliography">
                    { data.allReference.edges.map(edge => <BibEntry entry={edge.node} />) }
                  </div>
                )
            } else {
                return <p>No publications yet</p>
            }
          
        }
    }   
    />
}
```
Where BibEntry is a component that takes care of formatting the entries.

Hope this takes care of your issue :) If not, or if you have any suggestion, don't hesitate :)

**Comment by stschiff** [comment]
Fantastic, thanks for the fast response. I'll try it out. Who knows, maybe I'll contribute some documentation if I get it to work.

**Comment by stschiff** [comment]
Hmm. The problem is that `allReference` doesn't exist as query object, and neither do children of file nodes that contain BibTeX data. I think the plugin as such isn't working with the newest Gatsby version. I will try to debug somehow.

**Comment by giltho** [comment]
Hey :)
That's weird, I've just updated all my dependencies to the latest possible versions to see what would break and it seems that it still works
```js
"dependencies": {
    "bs-platform": "^7.2.2",
    "gatsby": "^2.21.5",
    "gatsby-plugin-manifest": "^2.4.1",
    "gatsby-plugin-offline": "^3.2.0",
    "gatsby-plugin-react-helmet": "^3.3.0",
    "gatsby-plugin-reason": "^2.1.0",
    "gatsby-plugin-sass": "^2.3.0",
    "gatsby-source-filesystem": "^2.3.0",
    "gatsby-transformer-bibtex": "^0.0.2",
    "node-sass": "^4.14.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^6.0.0"
  },
```
When you run `gatsby develop` do you have any part that fails or does it do nothing ?
Also, did you make sure to add `gatsby-transformer-bibtex` *after* `gatsby-source-filesystem` in your `gatsby-config.js` ?
```js
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `documents`,
        path: `${__dirname}/src/assets/documents`,
      },
    },
    'gatsby-transformer-bibtex',
```

**Comment by stschiff** [comment]
> Also, did you make sure to add gatsby-transformer-bibtex after gatsby-source-filesystem in your gatsby-config.js ?

Yes!
> When you run gatsby develop do you have any part that fails or does it do nothing ?

Yes, there are tons of errors and I had missed them before. sorry. Will inspect and report back.

**Comment by stschiff** [comment]
OK, apparently it throws a parsing error based on this field in one of my BibTeX entries:
`month    =  jun`
It says `Unresolved reference: "jun" ({"braceDepth":0,"stringref":"jun"})`.

So I guess my BibTeX file isn't behaving as intended in this package.

**Comment by stschiff** [comment]
OK, I replaced all `month` entries with curly brackets, so from `month = jun` I made `month = {jun}` and now it runs without error and I can see the references in the graphiQL browser. So looking good.

**Comment by giltho** [comment]
Cool ! Yeah, another solution would be `month = 6` here

I'm not really satisfied with the bibtex parsing story in the plugin.
I'm just using [bibtex](https://www.npmjs.com/package/bibtex) and getting things manually for there. You'll notice I only get a limited number of fields too, but that can be extended. Very little processing is done over them too...
There's very little tooling for bibtex processing in JS unfortunately :( I've tried bibliography.js but it was terrible

By looking at new solutions, [remark-bibliography] was released 3 months ago, it might be worth taking a look at how they do processing.
I'm adding improving this pluggin to my todo-list but I can't promise anything right now :/

If you it works and this issue is done, I'll let you close the issue :)

**Comment by stschiff** [comment]
Yes, I know it's only a limited nr of fields, but for now that's perfect for my case, where I just need a publication list on my webpage. The remark-bibliography thing is interesting, I will also keep an eye on that. I might add a bit documentation to your readme at some point and then send you a PR, but can't promise either.

I'm closing. Thanks again for your quick help!
