### ISSUE TITLE
Add support for 'slides' field

### ISSUE THREAD

**Issue by tobiasgrosser** [giltho/gatsby-transformer-bibtex#4]
Hi @giltho,

I am currently porting my website to gatsby. A field that I regularly use in my BibTeX files is the "slides" field. It mirrors the 'file' field you have for the pdf, but instead of the printed paper, it refers to a copy of the slide deck that I used to present this work.

You can find an example of such use here:

https://grosser.es/bibliography/doerfert2017optimistic.html

**Comment by giltho** [comment]
I'm not gonna release this one right away, do you mind depending on this unreleased commit until there's enough for 0.0.4 ? :)

**Comment by tobiasgrosser** [comment]
That works for me. I will be actively exploring your project for the next 1-2 weeks while porting my website. It is not unlikely that I have a couple more PRs, so I feel a couple of improvements might accumulate over the next weeks.
