### ISSUE TITLE
Obtain raw BibTeX

### ISSUE THREAD

**Issue by tobiasgrosser** [giltho/gatsby-transformer-bibtex#6]
Hi @giltho,

On my new website, I would like to make it easy for readers to get the BibTex for a given publication. I wonder if it would be possible to provide a 'raw' or 'bibtex' field that contains the full BibTeX string of a given entry.

**Comment by giltho** [comment]
This one was a bit tricky because the parser doesn't let me have the raw format back haha

**Comment by giltho** [comment]
fixed by 653c898

**Comment by tobiasgrosser** [comment]
Perfect. I tested it and it works as expected.
