### ISSUE TITLE
Add support for 'type' field

### ISSUE THREAD

**Issue by tobiasgrosser** [giltho/gatsby-transformer-bibtex#7]
@giltho,

I also use the 'type' field of BibTeX quite a bit to keep track of how my publications were published.

**Comment by giltho** [comment]
fixed by 653c898

**Comment by tobiasgrosser** [comment]
@giltho, here there seems to be a conflict:

There exists both the 'type' of a BibTeX entry as well as the 'type field' in a BibTeX entry: https://nwalsh.com/tex/texhelp/bibtx-47.html. It might make sense to think now about how to disambiguate them.

E.g., using:
  entry_type -> Entry Type
  type -> Field Type

I actually realized I am using both

**Comment by tobiasgrosser** [comment]
Another useful reference:

http://www.openoffice.org/bibliographic/bibtex-defs.html
